### ISSUE TITLE
How can I make the generated files public

### ISSUE THREAD

**Issue by ShulkMaster** [SunburstApps/ResourceGeneration#1]
The file generation and all its working fine but I do not know if there is any way to instruct the file generation with the public access modifier instead of internal?

**Comment by wjk** [comment]
First of all, please accept my apologies for not spotting this issue sooner. For some reason, I didn't get pinged when you created it.

As to your question: My code is already written to handle this case. Simply set the `%(EmbeddedResource.Visibility)` metadata on your restext file to "public" and rebuild. Note that this only works on restext files; you'll need to use the editor GUI to set the visibility of the code-behinds for RESX files, since they use a different mechanism. Hope this helps!

**Comment by ShulkMaster** [comment]
Don't worry I just end up adding the generated .Designer files to git so the CI could work.
That been said I'm the one who should apologize for closing the issue this fast without any explanation whatsoever, I thought the issue I oppened was kind of useless to begin with so I close it.
Anyway thank you for the suggestion comment I'll try it.

**Comment by ShulkMaster** [comment]
So you can do that by using the Visual Studio Resource editor, set the resource generation from `no code` to `Public` however by doing so VS will also mark the file as required to run custom tool to generate it, thus resulting in naming collision and duplicated simbols error. That can be fix by going to the properties panel in VS and under custom tool to run leave it blank and delete the pre build *.Designer.cs files them it will work
